# Generated by Django 4.2.2 on 2024-07-17 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0005_alter_student_fecha_ingreso_lic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matricula',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Sólo se permiten caracteres alfanuméricos.')]),
        ),
    ]
