# Generated by Django 4.1.7 on 2023-03-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0002_coordinador_estados_municipios_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='licenciatura_fei',
            field=models.CharField(blank=True, choices=[('', 'Seleccione...'), ('Estadística', 'Estadística'), ('Ingeniería de Software', 'Ingeniería de Software'), ('Ingeniería en Sistemas y Tecnologías de la Información', 'Ingeniería en Sistemas y Tecnologías de la Información'), ('Ingeniería de Ciberseguridad e Infraestructura de Cómputo', 'Ingeniería de Ciberseguridad e Infraestructura de Cómputo')], max_length=100, null=True),
        ),
    ]
