# Generated by Django 4.2 on 2023-04-21 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0002_coordinador_estados_municipios_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fecha_ingreso_lic',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2019)]),
        ),
    ]
