# Generated by Django 4.1.7 on 2023-03-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0002_coordinador_estados_municipios_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciatura',
            name='nombre_carrera',
            field=models.CharField(blank=True, choices=[('', 'Seleccione...'), ('Estadística', 'Estadística'), ('Ingeniería de Software', 'Ingeniería de Software'), ('Ingeniería en Sistemas y Tecnologías de la Información', 'Ingeniería en Sistemas y Tecnologías de la Información'), ('Ingeniería de Ciberseguridad e Infraestructura de Cómputo', 'Ingeniería de Ciberseguridad e Infraestructura de Cómputo'), ('Tecnologías Computacionales ', 'Tecnologías Computacionales'), ('Redes y Servicios de Cómputo ', 'Redes y Servicios de Cómputo')], max_length=60),
        ),
        migrations.AlterField(
            model_name='student',
            name='licenciatura_fei',
            field=models.CharField(blank=True, choices=[('', 'Seleccione...'), ('Estadística', 'Estadística'), ('Ingeniería de Software', 'Ingeniería de Software'), ('Ingeniería en Sistemas y Tecnologías de la Información', 'Ingeniería en Sistemas y Tecnologías de la Información'), ('Ingeniería de Ciberseguridad e Infraestructura de Cómputo', 'Ingeniería de Ciberseguridad e Infraestructura de Cómputo'), ('Tecnologías Computacionales ', 'Tecnologías Computacionales'), ('Redes y Servicios de Cómputo ', 'Redes y Servicios de Cómputo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sexo',
            field=models.CharField(blank=True, choices=[('', 'Seleccione sexo'), ('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Prefiero no decirlo')], max_length=10, null=True),
        ),
    ]
