# Generated by Django 4.1.7 on 2023-03-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0002_coordinador_estados_municipios_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pre_egreso_terminado',
            field=models.BooleanField(default=False),
        ),
    ]
