# Generated by Django 4.2 on 2023-05-16 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0002_carrera'),
    ]

    operations = [
     
        migrations.DeleteModel(
            name='Coordinador',
        ),
    ]
