# Generated by Django 4.1.7 on 2023-03-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0003_alter_licenciatura_nombre_carrera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pre_egreso_abierto',
            field=models.BooleanField(default=False),
        ),
    ]
