# Generated by Django 4.1.7 on 2023-04-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0003_student_pre_egreso_terminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='numero_exterior',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='numero_interior',
            field=models.IntegerField(null=True),
        ),
    ]
