# Generated by Django 4.1.7 on 2023-03-28 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0004_student_pre_egreso_abierto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matricula',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^S\\d{2}[0-9a-zA-Z]{6}$', 'La matrícula no es válida')]),
        ),
    ]
