# Generated by Django 4.1.7 on 2023-04-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0004_student_numero_exterior_student_numero_interior'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='localidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
