# Generated by Django 4.2 on 2023-05-17 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0005_carrera'),
    ]

    operations = [
       
    ]
