# Generated by Django 4.1.7 on 2023-04-12 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0006_alter_student_fecha_ingreso_lic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='celular_referencia_auxiliar',
        ),
        migrations.RemoveField(
            model_name='student',
            name='celular_referencia_principal',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nombre_referencia_auxiliar',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nombre_referencia_principal',
        ),
    ]
