# Generated by Django 4.2 on 2023-05-18 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0006_carrera'),
    ]

    operations = [
   
        migrations.AddField(
            model_name='student',
            name='pre_egreso_fecha_fin',
            field=models.DateField(null=True),
        ),
    ]
