# Generated by Django 4.1.7 on 2023-04-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0008_remove_student_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='post_egreso_abierto',
            field=models.BooleanField(default=False),
        ),
    ]
