# Generated by Django 4.1.7 on 2023-04-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0009_student_post_egreso_abierto'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nombre_ref_principal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
