# Generated by Django 4.1.7 on 2023-04-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0011_student_celular_ref_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nombre_ref_auxiliar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
