# Generated by Django 4.1.7 on 2023-04-12 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0012_student_nombre_ref_auxiliar'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='celular_ref_auxiliar',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Sólo se permiten números de teléfono de 10 dígitos.')]),
        ),
    ]
