# Generated by Django 4.1.7 on 2023-04-12 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0013_student_celular_ref_auxiliar'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='correo_alterno',
            field=models.CharField(blank=True, max_length=45, null=True, validators=[django.core.validators.RegexValidator('^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$', 'Sólo se permiten direcciones de e-mail válidas.')]),
        ),
    ]
