version: '3.7'

services:
    seguimiento_egresados:
        build:
            context: ./seguimiento_egresados
        ports:
            - "${APP_FORWARD_PORT:-80}:8000"
        volumes:
            -   ./seguimiento_egresados:/code
        command: >
            sh -c "python manage.py wait_for_db &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
        environment:
            - SECRET_KEY=devkey
            - DEBUG=1
            - DB_NAME=control_egresados
            - DB_TEST_NAME=test_control_egresados
            - DB_USER=adminsistemaegresados
            - DB_PASSWORD=&s00ftecHA
            - DB_HOST=bd_seguimiento_egresados
            - DB_PORT=3306
            - PATH_PREFIX=sse
            - EMAIL_PORT=${EMAIL_PORT}
            - EMAIL_HOST=smtp.gmail.com
            - EMAIL_HOST_USER=${EMAIL_HOST_USER}
            - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
            - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
            - SERVER_EMAIL=${SERVER_EMAIL}
        depends_on:
            - bd_seguimiento_egresados

    bd_seguimiento_egresados:
        image: mysql:8.4
        restart: unless-stopped
        ports:
          - '4060:3306'
        environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_DATABASE=${DB_NAME}
          - MYSQL_USER=${DB_USER}
          - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - sse_db_dev:/var/lib/mysql
volumes:
  sse_db_dev: