version: '3.7'

services:
  seguimiento_egresados:
    env_file:
      - seguimiento_egresados/seguimiento_egresados/settings.env
    environment:
      PATH_PREFIX: sse
    build: ./seguimiento_egresados
    restart: always
    container_name: seguimiento_egresados
    volumes:
      - ./seguimiento_egresados:/code
    depends_on:
      - bd_seguimiento_egresados  

  bd_seguimiento_egresados:
    image: mysql
    restart: unless-stopped
    env_file:
      - bd.env
    ports:
      - '4000:3306'
    volumes:
      - ./data:/var/lib/mysql
      - ./Scripts_SQL:/docker-entrypoint-initdb.d

  web_seguimiento_egresados:
    image: nginx
    restart: always
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./seguimiento_egresados/static:/static
    depends_on:
      - seguimiento_egresados
    environment:
      PATH_PREFIX: sse
    ports:
      - '8000:80'