# Generated by Django 4.2.2 on 2023-12-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinador',
            name='carrera_asignada',
            field=models.CharField(blank=True, default='Ninguna', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coordinador',
            name='correo',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='coordinador',
            name='nombre_completo',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
